name: ROTA
main: cat.nyaa.rota.ROTAPlugin
description: "ROTA"
version: ${version}
depend: [NyaaCore]
authors: [ReinWD]
website: "https://github.com/NyaaCat/ROTA"
database: false
api-version: 1.21

commands:
  rota:
    description: 'rota plugin admin command'
    permission: rota
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  rota:
    default: true
    description: 'root permission'
  rota.admin:
    default: op
    description: 'admin permission for ROTA plugin'
  rota.accept:
    default: true
    description: 'allow player to accept ROTA message.'
